name: Publish to PyPI

on:
  release:
    types: [created]               # triggers when release-please creates the GitHub release
  # push:
  #   tags: ['v*.*.*']                   # optional: also run when pushing tags like v1.2.3 (not recommended)

permissions:
  contents: read
  id-token: write                  # required for Trusted Publishing

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: python-dist
          path: dist/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/  # remove this line to publish to real PyPI
