name: Publish to PyPI

on:
  release:
    types: [created]               # triggers when release-please creates the GitHub release
  # push:
  #   tags: ['v*.*.*']                   # optional: also run when pushing tags like v1.2.3 (not recommended)

permissions:
  contents: read
  id-token: write                  # required for Trusted Publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - name: Download release archive
        uses: actions/download-artifact@v6
        with:
          name: python-package-distribution
          path: dist/
      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0             # needed if using setuptools_scm

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'

      # - name: Install build tools
      #   run: python -m pip install --upgrade build

      # - name: Debug git state
      #   run: |
      #     git fetch --tags --force
      #     git describe --tags --exact-match || echo "No exact tag match"
      #     git tag -l -n
      #     python -m setuptools_scm || echo "scm failed"

      # - name: Build package
      #   run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/  # remove this line to publish to real PyPI
